### ISSUE TITLE
Test https://beta.oerworldmap.org by @acka47

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#192]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [x] I receive the verification email ~and can click the link~ (I can not click the link as gmail identifies the email as phishing (see below))
- [x] I can log in with the new user
- [x] I can log back out
- [x] I can reset the password by entering the email
- [x] I can log in with the new password sent by email
- [x] I can change the new password to an own one
- [x] I can log in with the new password I supplied
- [ ] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [x] I can set and unset filters
- [x] I can show and hide the extended filter section
- [x] I can share, export and print the list
- [x] I can add one entry of each type
- [x] I can show the global statistics
- [x] I can list the recent additions
- [x] I can list the likes
- [x] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [x] I can find the data I expect
- [x] I can like ~and unlike the item~
- [x] I can add a lighthouse
- [x] I can set the `I'm a member` relation for organizations
- [x] I can set the `I'm attending` and `I am presenting` relation for events
- [x] I can add a comment
- [x] I can edit and save the entry
- [x] I can view the log of the entry (requires admin privileges)
- [x] I can delete comments (requires admin privileges)
- [x] I can delete lighthouses (requires admin privileges)

**Comment by acka47** [comment]
The sign up email is identified as phishing by gmail:

![bildschirmfoto vom 2018-04-03 14-36-22](https://user-images.githubusercontent.com/160292/38249607-83d48474-374c-11e8-9489-0ad8a884ad31.png)

**Comment by acka47** [comment]
#### Setting/unsetting filters

I am always irritated by the additional "Apply filter" button. Why not apply a filter directly when clicking on it and unset it when clicking it again?

#### Like/unlike

Unlike does not work for me. Instead of unliking I am logged out.

#### Misc

- I think we should add links to the logos of the "Development partners".
- When a detail view for an individual resource is opened I should be able to go back to the map by clicking besides the profile on the map. Currently, I have to click on the `x` to get back.

**Comment by acka47** [comment]
Please give admin privileges to pohl at hbz-nrw dot de

**Comment by literarymachine** [comment]
> The sign up email is identified as phishing by gmail:

I think this has to do with the mail server configuration, see hbz/oerworldmap#1468. I also think we should get support by hbz IT for this, maybe @philboeselager can look into this and talk to unix? This is not a new issue related to the rewrite btw.

> I am always irritated by the additional "Apply filter" button. Why not apply a filter directly when clicking on it and unset it when clicking it again?

Because then you cannot select multiple filter options at once. This has been decided I don't know when. We could change it in the future, but this is not part of the rewrite.

> Unlike does not work for me. Instead of unliking I am logged out.

Confirmed, see #199. We obviously only tested with admin accounts, where this does not occur.

> I think we should add links to the logos of the "Development partners".

Ack, see hbz/oerworldmap-static#2

> When a detail view for an individual resource is opened I should be able to go back to the map by clicking besides the profile on the map. Currently, I have to click on the x to get back.

Ok, we'll talk about this. Shouldn't be a show stopper for launching, right?

> Please give admin privileges to pohl at hbz-nrw dot de

Done.

**Comment by acka47** [comment]
>> When a detail view for an individual resource is opened I should be able to go back to the map by clicking besides the profile on the map. Currently, I have to click on the x to get back.

>Ok, we'll talk about this. Shouldn't be a show stopper for launching, right?

No, it isn't.

**Comment by acka47** [comment]
I checked the missing three items with admin privileges and it all works. Closing.
