### ISSUE TITLE
Test https://beta.oerworldmap.org by @trugwaldsaenger

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#193]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [x] I receive the verification email and can click the link
- [x] I can log in with the new user
- [x] I can log back out
- [x] I can reset the password by entering the email
- [x] I can log in with the new password sent by email
- [x] I can change the new password to an own one
- [x] I can log in with the new password I supplied
- [x] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [x] I can set and unset filters
- [x] I can show and hide the extended filter section
- [x] I can share, export and print the list
- [ ] I can add one entry of each type
- [x] I can show the global statistics
- [x] I can list the recent additions
- [x] I can list the likes
- [x] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [x] I can find the data I expect
- [x] I can like and unlike the item
- [x] I can add a lighthouse
- [x] I can set the `I'm a member` relation for organizations
- [x] I can set the `I'm attending` relation for events
- [x] I can add a comment
- [x] I can edit and save the entry
- [x] I can view the log of the entry (requires admin privileges)
- [x] I can delete comments (requires admin privileges)
- [x] I can delete lighthouses (requires admin privileges)

**Comment by trugwaldsaenger** [comment]
Habe (aus Versehen) versucht, eine lange Liste (alle Daten) als Jason zu exportieren. Der Exportvorgang hat ca. 2 Minuten gedauert, Abbrechen durch klicken auf das "x" war während dessen nicht möglich.

**Comment by trugwaldsaenger** [comment]
Export in Excel Funktioniert - ist aber nur bedingt menschenlesbar durch die vielen eingefügten URLs. Ist kein neues Problem des Refactorings, muss aber bei Gelegenheit nochmals angefasst werden.

**Comment by trugwaldsaenger** [comment]
Ausdruck einer Liste mit zwei Einträgen erfolgt auf drei Seiten:
1. Liste mit den beiden Namen 
2. Leerer Kartenausschnitt mit Legende und Zoom-Tasten
3. Leere Seite mit World Map URL

**Comment by trugwaldsaenger** [comment]
Second shown statistic is "Entries by secondary education". "Entries by primary sector" appears at the end of the list. This makes no sense. I think we already have ticket for this. "Entries by primary sector" should be moved up. # This should be solved before launch.

**Comment by trugwaldsaenger** [comment]
Recent additions can be shown. If I click on "more" the list appears and the map is shown again.

**This should be solved before launch.**

**Comment by trugwaldsaenger** [comment]
When trying to set a lighthouse without a comment the error-message "should have required property '@value'" appears. This should be changed in "Please enter a comment!"

**Comment by trugwaldsaenger** [comment]
I think Lighthouse Comments and Comments should be grafically seperated more from rest of the data.

**Comment by trugwaldsaenger** [comment]
When I`m setting a lighthouse, I cannot change the language of the comment.

**Comment by trugwaldsaenger** [comment]
Currently it is not possible to set a lighthouse for an event.

**This should be solved before the launch, if somehow possible.**

**Comment by trugwaldsaenger** [comment]
When edditing a field I now have to add a language manually. In the old version, it switched to "english" as soon as I started editing. I`m not shure, if this is a bug or a feature. I guess the solution on the new version provides more reliable results, but it is less confortable.

**This should be solved before the launch.**

**Comment by literarymachine** [comment]
> Wenn ich ein neues Passwort erstelle, dann muss ich dieses bestätigen, also zwei mal eingeben. Bei der Erstregistrierung ist dies nicht erforderlich. Eventuell angleichen?

This is a very common pattern, see e.g. Twitter:

![image](https://user-images.githubusercontent.com/149825/38725106-936478ce-3f06-11e8-9bab-c63ac8bb3966.png)

![image](https://user-images.githubusercontent.com/149825/38725120-9f5b03fa-3f06-11e8-8b47-8b11bf6d1691.png)

**Comment by literarymachine** [comment]
> Habe (aus Versehen) versucht, eine lange Liste (alle Daten) als Jason zu exportieren. Der Exportvorgang hat ca. 2 Minuten gedauert, Abbrechen durch klicken auf das "x" war während dessen nicht möglich.

Tested this repeatedly, Export time for all resources is around 1 second. I think the problem is that the resulting large JSON file is opened in the browser, which takes forever. We should send the file as a download if possible: hbz/oerworldmap#1474

**Comment by literarymachine** [comment]
> Export in Excel Funktioniert - ist aber nur bedingt menschenlesbar durch die vielen eingefügten URLs. Ist kein neues Problem des Refactorings, muss aber bei Gelegenheit nochmals angefasst werden.

Exactly, this is an open back end issue: hbz/oerworldmap#1432

**Comment by literarymachine** [comment]
>Ausdruck einer Liste mit zwei Einträgen erfolgt auf drei Seiten:
>
>- Leerer Kartenausschnitt mit Legende und Zoom-Tasten

Probably empty because the two entries don't have pins? We can hide the legend and the map controls.

>- Leere Seite mit World Map URL

Looking into this, too.

I recorded an issue here, we should think about what we actually want: #229.

**Comment by literarymachine** [comment]
> Second shown statistic is "Entries by secondary education". "Entries by primary sector" appears at the end of the list. This makes no sense. I think we already have ticket for this. "Entries by primary sector" should be moved up.

I agree that in case of primary / secondary sector it makes no sense. In general, we never specified an order, see #230.

**Comment by literarymachine** [comment]
> Recent additions can be shown. If I click on "more" the list ~~appears~~ disappears and the map is shown again.

See #231

**Comment by literarymachine** [comment]
> Currently it is not possible to set a lighthouse for an event.

Initially, lighthouses were only available for `Organization`, `Service` and `Project`, see hbz/oerworldmap#1128. This can be changed in the schema, see hbz/oerworldmap#1475.

**Comment by literarymachine** [comment]
> When edditing a field I now have to add a language manually. In the old version, it switched to "english" as soon as I started editing. I`m not shure, if this is a bug or a feature. I guess the solution on the new version provides more reliable results, but it is less confortable.

See #235
