### ISSUE TITLE
Test https://beta.oerworldmap.org by @karindr

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#194]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [x] I receive the verification email and can click the link
- [x] I can log in with the new user
- [x] I can log back out
- [x] I can reset the password by entering the email
- [x] I can log in with the new password sent by email
- [x] I can change the new password to an own one
- [x] I can log in with the new password I supplied
- [x] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [x] I can set and unset filters
- [x] I can show and hide the extended filter section
- [x] I can share, export and print the list
- [x] I can add one entry of each type
- [x] I can show the global statistics
- [x] I can list the recent additions
- [x] I can list the likes
- [x] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [x] I can find the data I expect
- [x] I can like and unlike the item
- [x] I can add a lighthouse
- [x] I can set the `I'm a member` relation for organizations
- [x] I can set the `I'm attending` relation for events
- [x] I can add a comment
- [x] I can edit and save the entry
- [x] I can view the log of the entry (requires admin privileges)
- [x] I can delete comments (requires admin privileges)
- [x] I can delete lighthouses (requires admin privileges)

**Comment by karindr** [comment]
When I got administration rights I can test the rest.

Should I add my findings to this issue?

**Comment by literarymachine** [comment]
> When I got administration rights I can test the rest.

Done!

> Should I add my findings to this issue?

Yes, please! We'll create according issues where necessary.

**Comment by karindr** [comment]
On production the log is opened in another tab on beta on the same tab. I like it better the way it is on production.

**Comment by karindr** [comment]
On production I can get rid of the list by clicking on "OER World Map" on beta the list stays there.
On production the map zoomes out when you click on "OER World Map" on beta the zoom level says the same.

**Comment by karindr** [comment]
What does the little arrow button next to the plus and minus botton means/does?

**Comment by karindr** [comment]
OK, understood.

**Comment by karindr** [comment]
On production you can mark for example 5 entries from the list and copy the text. On beta you can't copy more then one entry. I find it useful to be able to copy from the list.

**Comment by karindr** [comment]
It is great that you can change to an alphabetical order now. But the list of all entries starts with Contact North, ETH Zürich, iRights and Judith Smith-Meyer.

**Comment by karindr** [comment]
Logging in is quite slow and the screen does not show any reaction for some time. But you can't do anything wrong when you click again.

**Comment by karindr** [comment]
If I set a lighthouse and saved the comment. I am able to delete the comment (by closing the window when I deleted the comment (which I am not allowed to save). There should be a comment like "A lighthouse requires a comment to be published" instead of "should have required property '@value'".

**Comment by karindr** [comment]
What does the orange asterisk should mean? (After Comment in the lighthouse Template, after Name in the Add organisation template.)

**Comment by karindr** [comment]
When I clicked on I am a member the button gets orange. When I click again to say I am mot a member any more, the button becomes blue with white characters. That doesn't make sense.

**Comment by karindr** [comment]
There is "Add Description" below the description field in the input template. On production there was "Add language" which is clearer, best would be "Add description in another language"

**Comment by literarymachine** [comment]
> On production the log is opened in another tab on beta on the same tab. I like it better the way it is on production.

Fixed in https://github.com/hbz/oerworldmap-ui/pull/249

**Comment by literarymachine** [comment]
> On production you can mark for example 5 entries from the list and copy the text. On beta you can't copy more then one entry. I find it useful to be able to copy from the list.

Do you mean this? It also works on beta:

![image](https://user-images.githubusercontent.com/149825/38809199-0467b558-4183-11e8-8fef-3392be939b73.png)

Please clarify if you mean something else.

**Comment by literarymachine** [comment]
> It is great that you can change to an alphabetical order now. But the list of all entries starts with Contact North, ETH Zürich, iRights and Judith Smith-Meyer.

As discussed at the last team meeting, this must be fixed in the data. The names of those entries have trailing spaces, which come before the letters when sorting.

**Comment by literarymachine** [comment]
> Logging in is quite slow and the screen does not show any reaction for some time. But you can't do anything wrong when you click again.

From here it does not look any slower than currently on production. We might want to add the spinner to indicate the page is loading.

**Comment by literarymachine** [comment]
> If I set a lighthouse and saved the comment. I am able to delete the comment (by closing the window when I deleted the comment (which I am not allowed to save).

Sorry, I don't understand the problem. Can you clarify?

> There should be a comment like "A lighthouse requires a comment to be published" instead of "should have required property '@value'".

Yep, we have an issue for this: #232. Since this will require quite some translation etc, this is not going to be part of the relaunch though.

**Comment by literarymachine** [comment]
> What does the orange asterisk should mean? (After Comment in the lighthouse Template, after Name in the Add organisation template.)

Orange asterisks indicate required fields, which is a pretty common UI pattern. We might want to add a legend to the form though, or at least at a title to the asterisks.

**Comment by literarymachine** [comment]
> When I clicked on I am a member the button gets orange. When I click again to say I am mot a member any more, the button becomes blue with white characters. That doesn't make sense. Same for Presenting, Attending and the other buttons like these.

Actually, this is expected behavior and it does make sense, but we might need to change the styling. Blue with white characters indicates that the button is currently in focus (this also happens e.g. when you use the tab key to navigate with the keyboard), and it is after clicking.

**Comment by literarymachine** [comment]
> On production the log is opened in another tab on beta on the same tab. I like it better the way it is on production.

On beta.

**Comment by literarymachine** [comment]
> On production I can get rid of the list by clicking on "OER World Map" on beta the list stays there.
On production the map zoomes out when you click on "OER World Map" on beta the zoom level says the same.

On beta.

**Comment by literarymachine** [comment]
> What does the little arrow button next to the plus and minus botton means/does?

Got rid of this on beta.

**Comment by karindr** [comment]
Concerning "Mark entries in lists": Try to mark entries not starting with the first or the last but entries in the middle and then change to production. You will see the difference.

**Comment by literarymachine** [comment]
> Concerning "Mark entries in lists": Try to mark entries not starting with the first or the last but entries in the middle and then change to production. You will see the difference.

Beta:
![image](https://user-images.githubusercontent.com/149825/38853239-ee54f132-421c-11e8-827a-16babbf384ff.png)

Production:
![image](https://user-images.githubusercontent.com/149825/38853250-f811385c-421c-11e8-9ca0-682ab4b97542.png)

The only difference I see is that you have to start left of the icon on Beta.

**Comment by karindr** [comment]
Concerning the blue buttons with white letters: Understand this for navigating with tabs, but if you navigate with the mouse it is strange. you easily can get two blue buttons at the same time. Probably it is right like this, to me it looks like a bug.

**Comment by karindr** [comment]
Get it with the marking in the lists (hope the users will get it too ;-))

**Comment by karindr** [comment]
To the new lists:

- Changing from list entries 0 to 20 to list entries 20 to 40 is quite slow (but there is a spinner so it is ok).
- Printing the lists always prints the whole list. Being able to change how much entries are shown I expected this also being relevant for the printed list.

**Comment by karindr** [comment]
When I enter a search term to the search field the result list is by default sorted by date created. If I am searching for something I would expect relevance to be the default.

**Comment by karindr** [comment]
The new possibilities for setting tabs are great in will prevent a lot of wrong entring by useres!

**Comment by literarymachine** [comment]
> Concerning the blue buttons with white letters: Understand this for navigating with tabs, but if you navigate with the mouse it is strange. you easily can get two blue buttons at the same time. Probably it is right like this, to me it looks like a bug.

Yes, hover and focus style should not be the same! @dobladov already fixed this in https://github.com/hbz/oerworldmap-ui/pull/256, which I haven't deployed yet.

**Comment by literarymachine** [comment]
> When I enter a search term to the search field the result list is by default sorted by date created. If I am searching for something I would expect relevance to be the default.

You are right, as soon as a text is entered the list should be sorted by relevance: #257.

**Comment by karindr** [comment]
The entry testservice is located on the map in San Francisco (as its affiliated organisation) instead of being located in Cologne where its provider is located, see:
https://beta.oerworldmap.org/resource/urn%3Auuid%3A65acf8b9-1eab-4e84-ac56-497bb948cb9a

**Comment by literarymachine** [comment]
> Printing the lists always prints the whole list. Being able to change how much entries are shown I expected this also being relevant for the printed list.

I don't see this happening, e.g. this is a print of a list size `20`:
![image](https://user-images.githubusercontent.com/149825/38855880-1e40639c-4225-11e8-9ffb-e0d1d3c383d5.png)

**Comment by literarymachine** [comment]
> The entry testservice is located on the map in San Francisco (as its affiliated organisation) instead of being located in Cologne where its provider is located, see:
https://beta.oerworldmap.org/resource/urn%3Auuid%3A65acf8b9-1eab-4e84-ac56-497bb948cb9a

It is actually located in both, which I think is correct (only showing the provider location and not the affiliate I think is wrong on production, see https://github.com/hbz/oerworldmap/issues/1473#issuecomment-380049597). Try panning the map to Germany; but of course, both pins should be visible at the same time! @dobladov is there a way we can ensure all points are visible in `MiniMap`?

**Comment by karindr** [comment]
Printing on a real printer with paper ;-)

**Comment by karindr** [comment]
Concerning the Colours:
•	The first impression of the world map is much light green and very light green. I think that is not so good, because we should stress that the map is already filled with a lot of valuable data. We should think of a non-linear scale, especially when the biggest number is really big. For example on the start page it should be clearly visible that countries with only one entry are already displayed in a shade of green.
•	The blue of rivers and lakes is pretty the same as the blue of frontiers, that is not useful. It is better on production.
•	The frontiers of countries and smaller regional entities are nearly the same. They should be less strong.
•	There are different kinds of the map with a blue layer above it: When you click on the orange plus button and choose e.g. an organisation to add the map behind the template is light blue. When you click on the other orange buttons the map behind is darker.

**Comment by dobladov** [comment]
>both pins should be visible at the same time! @dobladov is there a way we can ensure all points are visible in MiniMap?

I think we can use `fitbounds`
- https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds

Here is an example https://www.mapbox.com/mapbox-gl-js/example/zoomto-linestring/

**Comment by literarymachine** [comment]
> Printing on a real printer with paper ;-)

Ok, but what do you mean with "Printing the lists always prints the whole list."? Since I cannot send paper over the wire, here is the PDF I get: [885 entries.pdf](https://github.com/hbz/oerworldmap-ui/files/1918923/885.entries.pdf)

It looks correct to me.

**Comment by literarymachine** [comment]
> Concerning the Colours:

If we want to address all of this before launch, we will not launch for OpenEd. @trugwaldsaenger what do you think?

**Comment by literarymachine** [comment]
> We should think of a non-linear scale

We are using a logarithmic scale: https://github.com/hbz/oerworldmap-ui/blob/master/src/components/Map.js#L407

**Comment by karindr** [comment]
Printing is ok.

**Comment by karindr** [comment]
Concerning the (text) design of the item view:
Example: https://beta.oerworldmap.org/resource/urn:uuid:3265edc9-f253-4a33-b953-8ee4ee826088

- There are two different shades of blue for words with links, is there any reason for that? If there is no reason I suggest changing to one colour.
- The tags are written in bold letters, why? They are emphasised by their blue colour, so they don’t need additional weight.
- It is hard to see because of the different blues, but I think the items in the right column like “Phillip von Böselager” are written in (semi)bold letters the items in the left column like “Early Childhood Education” are regular. Is there a reason? If no, use the same font weight.
- In both columns the distinction between smaller headings and text is not shown by the font. In the right column it is ok, because mostly there are links, so the text is blue and there is a line, but I think for the user it would be easier to find the information he is looking for, if the headings were different from the text (weight, size). A user will look for the word “Contact Person” od “Location” and then go on to “Domstraße” and “Phillip v. B.” so the headings should get more emphasis. In the left column it is especially bad for Abbreviation.
- One of the lines with most emphasis is “Add your comment*”. Is this line most important to us/for the user? I don’t think so. (By the way why is here an *? It is not a required field in a form.)
- There are the little twitter and fb-icons below the map. I expected them to be share links because they are located in the middle of a special page like the icons below a blogpost to share this post. The links to our twitter and our fb account should be in the header. (By the way the link on the twitter icon leads to twitter.com not to our account.)

**Comment by literarymachine** [comment]
> By the way the link on the twitter icon leads to twitter.com not to our account.

This is because you only entered `http://twitter.com` in the data.

**Comment by formimkontext** [comment]
> There are two different shades of blue for words with links, is there any reason for that? If there is no reason I suggest changing to one colour.

i think it is not only okay but helpful to give links different colors in different contexts. Making them all  ![#1A91E6](https://placehold.it/15/1A91E6/000000?text=+) blue would be pretty dazzling. the ![#0F578A](https://placehold.it/15/0F578A/000000?text=+) blue-dark is not working pretty well in smaller text sizes. 

> The tags are written in bold letters, why? 

just to make one tag (consisting several words) a more recognisable unit.  

> It is hard to see because of the different blues, but I think the items in the right column like “Phillip von Böselager” are written in (semi)bold letters the items in the left column like “Early Childhood Education” are regular. Is there a reason? If no, use the same font weight.

again: different information, different style. and like you said: 

> In both columns the distinction between smaller headings and text is not shown by the font. In the right column it is ok, because mostly there are links, so the text is blue and there is a line, but I think for the user it would be easier to find the information he is looking for, if the headings were different from the text (weight, size). A user will look for the word “Contact Person” od “Location” and then go on to “Domstraße” and “Phillip v. B.” so the headings should get more emphasis. In the left column it is especially bad for Abbreviation.

headings and text should be different. since allmost every entry within the lists beneath the tag-section is a link to another world map entry, its color would be blue. the abbreviation is an exception which i think, doesn’t need to be shown in the list but in the headline (abbreviation – full name).  

btw: didn’t we want hide the information about grade level, etc. by default and make the list expandable? 

> One of the lines with most emphasis is “Add your comment*”. Is this line most important to us/for the user? I don’t think so. 

i agree. can we do this like in this draft: https://user-images.githubusercontent.com/15141949/36307423-65eff280-131c-11e8-9e3f-fc2344d9040e.png

> There are the little twitter and fb-icons below the map. I expected them to be share links because they are located in the middle of a special page like the icons below a blogpost to share this post. 

those are the links to profiles elsewhere.

**Comment by formimkontext** [comment]
Concerning the Colours:
> If we want to address all of this before launch, we will not launch for OpenEd. @formimkontext
and @trugwaldsaenger what do you think?

maybe this seems to be a bigger issue than it realy is. 

> The first impression of the world map is much light green and very light green. I think that is not so good, because we should stress that the map is already filled with a lot of valuable data. We should think of a non-linear scale, especially when the biggest number is really big. For example on the start page it should be clearly visible that countries with only one entry are already displayed in a shade of green.

this is not about colors but our approach. i think it is okay. 

> The blue of rivers and lakes is pretty the same as the blue of frontiers, that is not useful. It is better on production.

> The frontiers of countries and smaller regional entities are nearly the same. They should be less strong.

you are right. i will change the styling of the boardes of the non colorpleth map.

> There are different kinds of the map with a blue layer above it: When you click on the orange plus button and choose e.g. an organisation to add the map behind the template is light blue. When you click on the other orange buttons the map behind is darker.

this is because some overlays are modals and the item view isn’t. @literarymachine i think we can adjust this without much effort, right?

**Comment by karindr** [comment]
> This is because you only entered http://twitter.com in the data.

And I chose a misleading example and was mislead ;-)

**Comment by karindr** [comment]
> the abbreviation is an exception which i think, doesn’t need to be shown in the list but in the headline (abbreviation – full name).

Yes, please hide the abbreviation in this list. It is not necessary here and makes several problems disappear!

> i agree. can we do this like in this draft: https://user-images.githubusercontent.com/15141949/36307423-65eff280-131c-11e8-9e3f-fc2344d9040e.png

This would be good.

> just to make one tag (consisting several words) a more recognisable unit.

You are right, this works quite well.

> btw: didn’t we want hide the information about grade level, etc. by default and make the list expandable?

I don't think we agreed on this and I don't think it is a good idea to hide these for teachers and students most importantant points about a service.

**Comment by karindr** [comment]
> headings and text should be different. since allmost every entry within the lists beneath the tag-section is a link to another world map entry, its color would be blue.

Form me there is not enough difference. Have a look at a screen like this:
![image](https://user-images.githubusercontent.com/18674205/38928085-032e1fca-4308-11e8-94d1-35d171442ed3.png)

**Comment by karindr** [comment]
Open problems transferred to other issues. closing
