### ISSUE TITLE
Test https://beta.oerworldmap.org by @drrobertfarrow

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#195]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [x] I receive the verification email and can click the link
- [x] I can log in with the new user
- [x] I can log back out
- [x] I can reset the password by entering the email
- [x] I can log in with the new password sent by email
- [x] I can change the new password to an own one
- [x] I can log in with the new password I supplied
- [ ] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [x] I can set and unset filters
- [x] I can show and hide the extended filter section
- [x] I can share, export and print the list
- [ ] I can add one entry of each type
- [x] I can show the global statistics
- [x] I can list the recent additions
- [x] I can list the likes
- [x] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [x] I can find the data I expect
- [x] I can like and unlike the item
- [x] I can add a lighthouse
- [x] I can set the `I'm a member` relation for organizations
- [x] I can set the `I'm attending` relation for events
- [x] I can add a comment
- [x] I can edit and save the entry
- [ ] I can view the log of the entry (requires admin privileges)
- [ ] I can delete comments (requires admin privileges)
- [ ] I can delete lighthouses (requires admin privileges)

**Comment by drrobertfarrow** [comment]
I seem to be waiting a little while for the confirmation email...

**Comment by drrobertfarrow** [comment]
Still no email :(

**Comment by drrobertfarrow** [comment]
"I can show the list by clicking on the list icon in the search box" - Yes, but the content is mostly things like "test"

**Comment by drrobertfarrow** [comment]
"I can list the likes" - I think so... when I click on the thumb button the map changes and I see only a handful of pins, mainly in Germany and USA

**Comment by drrobertfarrow** [comment]
OK, I seem to have reached the limit of what I can check without logging in...

**Comment by drrobertfarrow** [comment]
My conformation email was in the spam folder.  When I clicked on it though I get a blue screen (looks like the map but only sea) and the following error message: 

Client.Templates.http_error.title
Client.Templates.http_error.error
Bad Request

**Comment by literarymachine** [comment]
> "I can show the list by clicking on the list icon in the search box" - Yes, but the content is mostly things like "test"

Yes, because people are testing and things are ordered by `dateCreated`. Did you see the possibility to page through the results?

> "I can list the likes" - I think so... when I click on the thumb button the map changes and I see only a handful of pins, mainly in Germany and USA

Right, the behavior is as currently in production.

> My conformation email was in the spam folder. When I clicked on it though I get a blue screen (looks like the map but only sea) and the following error message:

Ok, something definitely went wrong there. Your [profile](https://beta.oerworldmap.org/resource/urn%3Auuid%3Ad579c599-9877-49d8-ad0c-e4ab29aafe0b) is activated though, so your account was confirmed and you should be able to log in. Any chance you reloaded the page after registering? Once clicked, the token is invalid.

**Comment by literarymachine** [comment]
> My conformation email was in the spam folder.

Recorded as hbz/oerworldmap-static#2

**Comment by drrobertfarrow** [comment]
I tried resetting the password and now I seem to be able to log in OK!

**Comment by drrobertfarrow** [comment]
I get an error message when trying to add an organisation 
![screen shot 2018-04-06 at 14 31 47](https://user-images.githubusercontent.com/10849418/38423937-5049dcdc-39a7-11e8-9607-4b05e793465e.png)

**Comment by literarymachine** [comment]
> I get an error message when trying to add an organisation

Yes. Try selecting...the "required property language".

**Comment by drrobertfarrow** [comment]
I get similar issues when trying to add a service and I can't see how to assign a location to an entry... 
![screen shot 2018-04-06 at 14 33 46](https://user-images.githubusercontent.com/10849418/38424014-96facef2-39a7-11e8-94a4-e934c092d707.png)

**Comment by literarymachine** [comment]
Yes. Those are error messages trying to tell you that you did not enter all necessary information. They could be more user friendly, but this is currently expected behavior.

**Comment by literarymachine** [comment]
> I can't see how to assign a location to an entry...

Try setting a `Country`.

**Comment by literarymachine** [comment]
> I can't see how to assign a location to an entry...

Setting the country is enough. The error messages do not update in real-time though. The error should disappear the next time you try to save. If all of this is too confusing, we could move all error messages above the form as is the case currently on production.

**Comment by drrobertfarrow** [comment]
OK, I think I got the hang of it now.  https://beta.oerworldmap.org/resource/urn:uuid:2ffbbbb7-cdeb-492c-ab49-eac75641800b

I think it would be helpful if you could select a language once rather than selecting it for each field.  Surely they will usually all be in the same language? 

Also, maybe abbreviations don't need a language property ...?

**Comment by literarymachine** [comment]
> I think it would be helpful if you could select a language once rather than selecting it for each field.

What we currently have (on production) is that the language always defaults to English as soon as something is typed in the field. We might need to re-implement that.

> Surely they will usually all be in the same language?

Usually yes, but not necessarily always. People actually do enter information in multiple languages.

> Also, maybe abbreviations don't need a language property ...?

This is a question of the data model, it has been as is since the beginning. @acka47 do you see a need to change things here?

**Comment by acka47** [comment]
>> Also, maybe abbreviations don't need a language property ...?

> This is a question of the data model, it has been as is since the beginning. @acka47 do you see a need to change things here?

I found it a bit strange myself when editing a test entry. However, institutions do exist that hve different abbreviations depending on the language (e.g. [WTO](https://www.wikidata.org/wiki/Q7825)) and someday such an international institution might turn up in the world map...
