### ISSUE TITLE
Test https://beta.oerworldmap.org by @philboeselager

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#197]
# [Landing Page](https://beta.oerworldmap.org)
- [x] I can click on all links

# [User registration](https://beta.oerworldmap.org/user/register)
- [x] I can register a user
- [x] I receive the verification email and can click the link
- [x] I can log in with the new user
- [x] I can log back out
- [x] I can reset the password by entering the email
- [x] I can log in with the new password sent by email
- [x] I can change the new password to an own one
- [x] I can log in with the new password I supplied
- [ ] I can administer groups (requires admin privileges)

# [Map / List](https://beta.oerworldmap.org/resource/)
- [x] I can move around on the map
- [x] I can click on large clusters of pins to zoom in
- [x] I can click on small clusters of pins to get a list popup
- [x] I can click on individual pins
- [x] I can show the list by clicking on the list icon in the search box
- [x] I can set and unset filters
- [x] I can show and hide the extended filter section
- [ ] I can share, export and print the list
- [x] I can add one entry of each type
- [x] I can show the global statistics
- [x] I can list the recent additions
- [x] I can list the likes
- [x] I can list the lighthouses

# [Individual items](https://beta.oerworldmap.org/resource/urn%3Auuid%3A29056e88-727b-407e-b00a-16df279ac506)
- [x] I can find the data I expect
- [x] I can like and unlike the item
- [x] I can add a lighthouse
- [x] I can set the `I'm a member` relation for organizations
- [x] I can set the `I'm attending` relation for events
- [x] I can add a comment
- [x] I can edit and save the entry
- [ ] I can view the log of the entry (requires admin privileges)
- [ ] I can delete comments (requires admin privileges)
- [ ] I can delete lighthouses (requires admin privileges)

**Comment by philboeselager** [comment]
Everything went mainly as expected, except I couldn't find how to "share, export and print the list". Rest will be put into issues.

**Comment by literarymachine** [comment]
> Everything went mainly as expected, except I couldn't find how to "share, export and print the list".

![image](https://user-images.githubusercontent.com/149825/38298391-7f211b80-37f7-11e8-9d2b-2970829e2094.png)

> Rest will be put into issues.

Please comment here, @dobladov and I will create / link to issues.

**Comment by philboeselager** [comment]
Weird filter (?) display
https://beta.oerworldmap.org/resource/
![oerwm-ui_filterview](https://user-images.githubusercontent.com/10129448/38313627-c6c4f7fe-3824-11e8-8bdc-bf98f0120b67.png)
(Ubuntu / Chromium)

**Comment by philboeselager** [comment]
No fitting map hit for „Jülicher Straße 4, Köln“
https://beta.oerworldmap.org/resource/?add=Organization
There are many map results but only for other towns.
Does not seem to be an UI issue.

**Comment by philboeselager** [comment]
Add organization: „%s hinzufügen“ (Ubuntu / Chromium)
https://beta.oerworldmap.org/resource/?add=Organization
Every form entry is subtitled by „%s hinzufügen“.

**Comment by literarymachine** [comment]
> Menu language changes to English when clicking on „Beitragen“ (showing English „Contribute“ page).

Right, the proxy currently discards the language and always points to the English static pages. See #207.

> Country coloration is only visible for some countries (US, Canada & Germany)
> Other countries appear to be too light. Maybe use a logarithmic scale here.

The choropleth depends on the filters that are currently applied. But also if none are set, only three colors from the legend seem to be actually used:
![image](https://user-images.githubusercontent.com/149825/38316267-9a06011c-382a-11e8-9f07-4c79753b7840.png)
@dobladov can you take a look at #208

> Defect map view when returning from hibernate mode (Ubuntu / Chromium)

This seems to be a browser / OS / WebGL issue that we'll have to accept for now.

> Map is centered on U.S. on startup (Ubuntu / Chromium)

Confirmed. Is this on purpose, @dobladov?

> Registration country select input field should directly be active
Clicking „select“ in the Registration section opens a list of countries with an input field on top. This input field is only active after clicking into it. (Ubuntu / Chromium)

Not a show stopper, but definitely +1: #209

> Registration confirmation: „Nutzer %s verifiziert.“ (Ubuntu / Chromium)
> Weird filter (?) display
> Add organization: „%s hinzufügen“ (Ubuntu / Chromium)
> Every form entry is subtitled by „%s hinzufügen“.

Right, we need to port a couple of changes in the i18n back to other languages. And we need to re-configure crowdin. See #210.

> No fitting map hit for „Jülicher Straße 4, Köln“
> Does not seem to be an UI issue.

This is indeed an issue with the data delivered by [Nominatim](https://nominatim.openstreetmap.org/search.php?q=J%C3%BClicher+Stra%C3%9Fe+4%2C+K%C3%B6ln&polygon_geojson=1&viewbox=). I discussed using the hbz Pelias instance with @dr0i, but this will require some additional set up and testing upfront. For now, user will have to live with our explanation: ` If you cannot find your exact address, try omitting the house number or enter only the city. Then fill in the details and drag the pin to the correct location below.`
