### ISSUE TITLE
"Unliking" not possible by non-admins

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#199]

**Comment by acka47** [comment]
It works, but when I unlike the button is blue as if I'd hover over it although I don't. Clicking anywhere makes it turn white. That's a bit strange.

**Comment by dobladov** [comment]
> Clicking anywhere makes it turn white

This is because we use a blue background for the hover/focus event; when you unlike, the button is still focus and therefore still blue, we could chose a different aproach like using only the outline for the focus event.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/commit/0ec208c0d3864842379ae5af3b1da390830fd319
