### ISSUE TITLE
Specify order of statistics

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#230]
Second shown statistic is "Entries by secondary education". "Entries by primary sector" appears at the end of the list. This makes no sense. I think we already have ticket for this. "Entries by primary sector" should be moved up.

**Comment by literarymachine** [comment]
Fixed on beta, see https://beta.oerworldmap.org/aggregation/

**Comment by trugwaldsaenger** [comment]
+1
