### ISSUE TITLE
Add note to Lighthouse form

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#234]
When setting a lighthouse, it should be mentioned, that lighthouses should not set by persons affiliated to the entry.

**Comment by acka47** [comment]
I already proposed a wording at https://github.com/hbz/oerworldmap/issues/1437#issuecomment-362592690.

**Comment by literarymachine** [comment]
> I respectively @trugwaldsaenger already proposed a wording at hbz/oerworldmap#1437 (comment).

Ah ok, great!

**Comment by literarymachine** [comment]
I'll put only `Please set lighthouses only in case you are not affiliated with the entry in any way!` on the form.

**Comment by literarymachine** [comment]
Fixed on beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:def7377c-b3a0-4bf9-ad9d-2bc03c55c8ca#addLighthouse

**Comment by trugwaldsaenger** [comment]
+1
