### ISSUE TITLE
Move awards and licenses beneath Likes

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap-ui#251]

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn%3Auuid%3Aef63568b-9e81-4003-9aa5-54ddff99f9d3

We decided to leave the license at the bottom for now because it looked a bit bulky to have them below the award logo.

**Comment by trugwaldsaenger** [comment]
Many thanks for your quick and flexible reaction! I can understand the visual argument. We can discuss this issue later on. My general idea was that information that is needed to evaluate the service should be provided before information, which is needed to contact the service. But - as I said - we can keep it like this for now!

**Comment by literarymachine** [comment]
Closed in #253.
