### ISSUE TITLE
Country level map - possible bugs or edits needed?

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap-ui#318]
[
![screen shot 2018-05-29 at 13 32 28](https://user-images.githubusercontent.com/10849418/40659031-fa7afd82-6344-11e8-8c26-2e7ec8f70b32.png)
](url)
Looking at the UK map:  the heatmap looks a bit strange at the county/state level for the UK.  There are counties which are displaying white when there are dots within the region.

The language for "Country champion available" seems a bit off - it could mean its opposite.  If it means that there is a country champion in place I'd just say that.

The county level may not be the most appropriate for the UK as it looks like all activity is concentrated in a handful of places.  But the activities of these institutions may not be contained within a particular county.  

Maybe it's a bug?

**Comment by acka47** [comment]
Duplicate of https://github.com/hbz/oerworldmap/issues/1484 and https://github.com/hbz/oerworldmap/issues/1555. @literarymachine explained why this happens in https://github.com/hbz/oerworldmap/issues/1555#issuecomment-392885771:

> For the coloring, the region has to be specified (so that nobody is forced to give an exact location to be counted in the choropleth map). For the UK, a lot of entries [are missing the region but have a pin](https://oerworldmap.org/country/gb?q=_exists_:about.location.geo%20AND%20_missing_:about.location.address.addressRegion). This has to be fixed on the data level by setting the region.

Closing.

**Comment by drrobertfarrow** [comment]
I am just entering some data and have been forced to select a region (in Sweden) before I can enter an address for the record.  I assume this is in response to this issue - The only thing I would note about it is that is makes a significant addition to work flow as I then had to go and look up regions in Sweden on Wikipedia, etc.  In the long run it would be preferable if the region could be calculated automatically from the address (though I don't know how practical this is).  Admittedly, if you are entering data from a region closer to home this is probably less of an issue.  But for country champions who represent large geographical areas this could be a source of frustration.

**Comment by literarymachine** [comment]
> I am just entering some data and have been forced to select a region (in Sweden) before I can enter an address for the record.

No, you don't have to enter a region:

![image](https://user-images.githubusercontent.com/149825/41963456-f28fb8c8-79f7-11e8-93ce-613a9ac33a64.png)

This was fixed in #302. What makes you think you have to enter a region?

**Comment by literarymachine** [comment]
The Address lookup works without selecting a region, too:

![image](https://user-images.githubusercontent.com/149825/41963587-38937882-79f8-11e8-802a-c002ebcc6806.png)

**Comment by literarymachine** [comment]
> In the long run it would be preferable if the region could be calculated automatically from the address (though I don't know how practical this is).

We have been looking into this, and perhaps surprising have not found an API that provides consistent region codes along with the addresses.
